### ISSUE TITLE
Enginewrapper is not defined

### ISSUE THREAD

**Issue by MightEnlightenYou** [e-p-armstrong/augmentoolkit#13]
I'm being lazy with the issues but I don't know how to fix them so I might as well just post them

![image](https://github.com/e-p-armstrong/augmentoolkit/assets/86793055/ce1a687e-0f08-4fdb-86f1-f224f118c9ab)

**Comment by e-p-armstrong** [comment]
In this case, the IDE is wrong, and the code will still work. This is due to the strange way some stuff is imported. Those decisions were mostly influenced by legacy requirements that no longer apply though, so to clean things up I added a conventional import.

Thanks for using Augmentoolkit!
