### ISSUE TITLE
Processing.py running into an error

### ISSUE THREAD

**Issue by sp93** [e-p-armstrong/augmentoolkit#17]
![Screenshot 2024-05-17 084518](https://github.com/e-p-armstrong/augmentoolkit/assets/15993894/5cf9d499-1217-45d9-b045-6c9783035ffd)
 Never ran into this before. My input folder had only one txt file.

**Comment by e-p-armstrong** [comment]
Good catch. Seems the PR by cocktailpeanut broke generation under some circumstances, including the default one.

Fixed on my end, lmk if it works for you!

**Comment by sp93** [comment]
Its working now. Thanks!
