### ISSUE TITLE
Recommendation: when training on Augmentoolkit data, use GaLore, NOT LoRAs

### ISSUE THREAD

**Issue by bodybreaker** [e-p-armstrong/augmentoolkit#19]
Hi, 
Is there any reason for
"Recommendation: when training on Augmentoolkit data, use GaLore, NOT LoRAs"

**Comment by e-p-armstrong** [comment]
GaLore is like a full finetune; it's far more effective for teaching models factual information. LoRAs are mostly for stylistic adjustments.
