### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ngoiyaeric** [e-p-armstrong/augmentoolkit#21]
<img width="1081" alt="Screen Shot 2024-06-06 at 2 12 41 PM" src="https://github.com/e-p-armstrong/augmentoolkit/assets/115367894/56072c8b-ccc5-4245-bc25-d4fc75d032b7">

**Comment by ngoiyaeric** [comment]
I'm using api mode still prompts for afrodite config files looks good.

**Comment by worstkid92** [comment]
> I'm using api mode still prompts for afrodite config files looks good.

Got same error. Do you have any updates on this?
