### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 430: character maps to <undefined>

### ISSUE THREAD

**Issue by BovineOverlord** [e-p-armstrong/augmentoolkit#31]
When running processing.py I encounter the following error- 

Traceback (most recent call last):
  File "D:\AI\LLM\augmentoolkit-master\processing.py", line 422, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\AI\LLM\augmentoolkit-master\processing.py", line 77, in main
    control_flow_functions.create_pretraining_set(
  File "D:\AI\LLM\augmentoolkit-master\augmentoolkit\control_flow_functions\control_flow_functions.py", line 1427, in create_pretraining_set
    file_contents = file.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 430: character maps to <undefined>

There is a similar issue someone else is having, where adding "encoding="utf-8"" fixes it, however this does not work here.

**Comment by BovineOverlord** [comment]
Nvm I fixed it myself. Requires chardet. Here are the altered files in txt format as py is not allowed. Just change the file type back to py.
[processing.txt](https://github.com/user-attachments/files/16120654/processing.txt)
[control_flow_functions.txt](https://github.com/user-attachments/files/16120656/control_flow_functions.txt)

**Comment by BovineOverlord** [comment]
No problem.
Depends on what you mean by a PR.
Also this only fixes it when running from processing.py, not app.py. I'll send the fix for that later today.

**Comment by BovineOverlord** [comment]
[app.txt](https://github.com/user-attachments/files/16137195/app.txt)
Here you go, same deal. To summarize the issue, python defaults to cp1252 encoding, but Windows defaults to UTF-8. This isn't always an issue, but if there are characters within the UTF-8 file that cp1252 cannot convert, it throws an error. So we use chardet to detect the encoding and use the appropriate one to handle the file. This should prevent an issue with Linux users, someone else will need to confirm.

**Comment by BovineOverlord** [comment]
Okay I think I figured it out and pushed the changes, let me know if you have any questions.

**Comment by e-p-armstrong** [comment]
Hey thanks for making the PR! And really sorry for the delay in getting it in here. GitHub did an annoying thing and made it so that if I had just clicked the "merge" button I would've overwritten a bunch of more recent work, so I had to manually go through it.

As of this latest push, your changes should be in! Thanks for your contribution to Augmentoolkit :)
