### ISSUE TITLE
How do you use this with Ollama locally?

### ISSUE THREAD

**Issue by jsauerland** [e-p-armstrong/augmentoolkit#40]
Question. How do you use this with Ollama installed on a local PC? I was following web UI tutorial, and was not able to get it setup for local Ollama 3 instance. Issue I faced was being unable to get past config.yaml step, since I don't have an API key.

**Comment by AllyourBaseBelongToUs** [comment]
what specifically?

You used ollama serve and the model you wish? (alternativly just ollama run and your preferred model, as it runs in the background anyway)

then in the gradio you can add the name of the model, like llama3 or whatever you have installed (make sure to type the full name)

or share your config file and ill help

**Comment by e-p-armstrong** [comment]
@jsauerland Just a note w.r.t. the API key thing -- if you're doing local inference, you can put literally anything there, so long as you don't leave it empty (this will result in the API request having a syntax error basically). So, you don't need a key but you DO need to put something there.

Thanks @AllyourBaseBelongToUs for supporting people btw!

**Comment by jsauerland** [comment]
Thanks everyone for the info

**Comment by beingretrogamer** [comment]
I have a M2 Pro and still the process is pretty slow with just 33 chunks. Is there a way I can improve the speed? I believe, my machine is powerful enough?

**Comment by JRDK92** [comment]
> I have a M2 Pro and still the process is pretty slow with just 33 chunks. Is there a way I can improve the speed? I believe, my machine is powerful enough?

I'd recommend asking a question in a new thread/post. Typically not advised to necro an old post to get an answer 😅
