### ISSUE TITLE
"Invalid 'stop': array too long Open AI API

### ISSUE THREAD

**Issue by kmahorker** [e-p-armstrong/augmentoolkit#41]
The open ai reference allows a maximum of 4 stop words. Using the OpenAI API errors out most of the generator functions. 

Can we add an option for a shortlist of stop words?

<img width="505" alt="image" src="https://github.com/user-attachments/assets/a4fff1c1-7cbc-421e-ae2f-3d0ad0e2a412">

**Comment by e-p-armstrong** [comment]
I believe there is an option in the config for this already. under SYSTEM, look for "STOP". Set it to false and it truncates the stop token lists to make it work w/ OAI. Maybe a bit hacky? But it should "solve" the problem?

 A Shortlist is a better solution, you're right.
