### ISSUE TITLE
'Did not contain a determination! MEGA MODEL FAIL LOOK INTO THIS EVAN!!!'

### ISSUE THREAD

**Issue by JamieAGP** [e-p-armstrong/augmentoolkit#42]
I have ran the tool fine with different input data that was smaller and contained less technical/specific text. I since moved onto some more technical text (niche software user guide) and have ran it multiple times to end up with empty 'simplified_data_no_rag.jsonl', 'simplified_data_rag.jsonl' and 'processed_master_list.json' files.

I am hosting a local server using LM studio, and have ran it using Phi-3 (worked for my previous input data) and llama-3 7B.

It seems to run as expected up to the revision stage:
`-------------- QUESTIONS CREATED ------------- STATS SO FAR (may be wrong if run was continued from interruption):
Nones: 132
Non-nones: 204
Total: 336`

However in the revision I repeatedly get this error for every iteration:
`Did not contain a determination! MEGA MODEL FAIL LOOK INTO THIS EVAN!!!
Output written to ./output_6/question_context_revision_generations\aee441ee-fc34-416b-81c0-7c484fcea258.yaml`

Then in the examples generation section, every conversation is too short:
`Output written to ./output_6/multiturn_conversation_generations\960b902e-eb20-4832-b30c-386fc57d64a0.yaml
Conversation is too short! Validation failed!
[]
----------------`

Is there a solution here? I have tried the two different models, I have tried changing the 'DOUBLE_CHECK_COUNTER'. The only thing I have not tried (until later today) is to change the 'FINAL_ASSISNTANCE_PROMPT' RAG and NO_RAG. I edited it to be specific for my use case whereas with the previous input data (which worked) I left it as is.

**Comment by e-p-armstrong** [comment]
It looks like question generation is working,  but the issue is that it's failing during the revision step. This is a bit unusual, maybe it has to do with the input text or the model you're running with — one third failed questions is a really elevated error rate for that step.

Could you share your config? And your `output` folder? There all intermediate generations, efvfen failed ones, are saved there -- will be useful for debugging.

Also as a note: the FINAL_ASSISTANT_PROMPT rag and no rag just determine what the system prompt added to the datasets at the end of everything is. It doesn't actually have an impact on generation.

Finally -- are you sure taht *every* conversation is failing validation? It seems there might be a difficult input text because of the elevated errors during question generation, but I'd expect a few things to get through even if just through chance alone. Unless the LLM being a bit too unintelligent is the problem?

**Comment by JamieAGP** [comment]
Yes exactly, questions are being generated. The input text is very niche, and you will have to forgive me for not noting down this exact error message and I don't know how to reproduce it, but at one point I remember seeing something along the lines of 'Question is too technical...can't rely on the accuracy'.

The output folder in a google drive [here](https://drive.google.com/drive/folders/1vbQpBkkGqIywFxyYQEQ4OuKOpZ1nyXUr?usp=sharing) and I can't attach a .yaml file so here is the text:

`
# Config
PATH:
  INPUT: "./user_guide"
  OUTPUT: "./output"
  DEFAULT_PROMPTS: "./prompts" # the baseline prompt folder that Augmentoolkit falls back to if it can't find a step in the PROMPTS path
  PROMPTS: "./prompts" # Where Augmentoolkit first looks for prompts
API:
  API_KEY: "DUMMY" # Add the API key for your favorite provider here
  BASE_URL: "http://localhost:1234/v1/" # add the base url for a provider, or local server, here. Some possible values:  http://127.0.0.1:5000/v1/ # <- local models. # https://api.together.xyz # <- together.ai, which is real cheap, real flexible, and real high-quality, if a tad unreliable. # https://api.openai.com/v1/ # <- OpenAI. Will bankrupt you very fast. # anything else that accepts OAI-style requests, so basically any API out there (openrouter, fireworks, etc etc etc...)
  LOGICAL_MODEL: "meta-llama/Llama-3-8b-chat-hf" # model used for everything except conversation generation at the very end
  LARGE_LOGICAL_MODEL: "meta-llama/Llama-3-70b-chat-hf" # model used for question generation and conversation generation at the very end. A pretty tough task, if ASSISTANT_MODE isn't on.
  QUANTIZATION_SMALL: "gptq" # Only use if Aphrodite mode is on.
  QUANTIZATION_LARGE: "gptq" # Only use if Aphrodite mode is on.
SKIP:
  QUESTION_CHECK: False
  ANSWER_RELEVANCY_CHECK: False # turn on if using the negative question prompt override
SYSTEM:
  CHUNK_SIZE: 1900
  USE_FILENAMES: False # give the AI context from the filenames provided to it. Useful if the filenames are meaningful, otherwise turn them off.
  DOUBLE_CHECK_COUNTER: 1 # How many times to check a question and answer pair during each validation step. Majority vote decides if it passes that step. There are three steps. So most questions are by default checked around 9 times (fewer if the first two checks for a step pass, obviously).
  SUBSET_SIZE: 1500
  USE_SUBSET: False # Whether to take only the first 13 chunks from a text during the run. Useful for experimenting and iterating and seeing all the steps without costing too much money or time.
  CONCURRENCY_LIMIT: 50 # Hard limit of how many calls can be run at the same time, useful for API mode (aphrodite automatically manages this and queues things, as far as I know)
  COMPLETION_MODE: False # Change to false if you want to use chat (instruct) mode; this requires .json files in your chosen prompts directory, in the OpenAI API format. Not all APIs support completion mode.
  MODE: "api" # can be one of "api"|"aphrodite"
  STOP: True # True = Use stop tokens, False = do not use stop tokens. OpenAI's API restricts you to four stop tokens and all steps have way more than four stop tokens, so you'll need to turn this to False if you're using OAI's API. Also NOTE that if you turn this OFF while using COMPLETION MODE, EVERYTHING WILL BREAK and it will cost you money in the process. Don't do that.
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between a generalist, generic AI assistant, and a human.
  FINAL_ASSISTANT_PROMPT_NO_RAG: |
   You are a helpful AI assistant.
  FINAL_ASSISTANT_PROMPT_RAG: |
   You are a helpful AI assistant.

   Context information is below:
   
   ----------------------
   {data}
PHASE:
  WORK_IN_PHASES: False
  PHASE_INDEX: 3 # index of the phase we are currently on (index 0 = filtering out chunks with no relevant context; index 1 = question generation; index 2 = question validation; index 3 = context revision and conversation generation, the final phase)
`

I am using LM studio to create a local HTTP server, so from what I understand it doesn't matter what I put for 'LOGICAL_MODEL' and 'LARGE_LOGICAL_MODEL'. This worked for the simpler dataset, so I am thinking is that it could be the model that is causing the issue. I am using LLama 3.1 8B which I thought was powerful enough.

Regarding every question failing, I am not so sure as I am still learning the tool. No conversations end up in master_list.jsonl or in the simplified_data files, but in 'muliturn_conversation_generations' the conversations generated are of good quality just too short it seems.

I will also mention that the run that worked was forked from an earlier version, before the charmap issue where the tool had an issue recognizing certain characters in the input text, so the config in that version was without the PHASE section.

Unless you can see somewhere I am going wrong, I think I will try with a more powerful model. Thanks for the help.

**Comment by e-p-armstrong** [comment]
Hey, thanks for your patience! Just checked the intermediate logging you shared in your google drive (very, very useful! Thank you!) and found what seems to be the error:

![image](https://github.com/user-attachments/assets/6bdff68b-5fab-4541-a51c-c71ae104cc94)

For some reason literally all of your context revision steps stop after writing "## Reasoning and thought process". Looking at your config it seems you're running a local model. Could this be related to that model's prompt format, stop tokens, or some settings on your local server? Either way I'd look into what's causing your model to stop generating at that point every time.

**Comment by JamieAGP** [comment]
Thanks for that, I would have spent a long time before I noticed that!

I've had another few looks since your reply and what seems to work is when I use the PHASE options. I used the subset option with the same model I was running locally as before, but I have manually done each phase and used the resume capability - all with the same model however. 

The results are promising whereas before I had nothing, so going to do the full run and will hopefully continue with the same success.

**Comment by JamieAGP** [comment]
The full run worked well on my local model when using the phases. Here are the output files incase you wanted them - just as I didn't change anything with my local model so thought you may be interested.

https://drive.google.com/drive/folders/16N5-4jgp5CNN9VCAEBO5UcoQ_csdm9pX?usp=sharing
