### ISSUE TITLE
Generation is not working 

### ISSUE THREAD

**Issue by MSR2201** [e-p-armstrong/augmentoolkit#44]
![image](https://github.com/user-attachments/assets/bd9c26fa-12c5-48aa-ae9a-b91d14f42da2)
i am getting the above error but the data is in the txt file in the designated folder
even though this is not my data it is generating something else
![image](https://github.com/user-attachments/assets/a2a47a53-9102-40f8-946a-e7211a705e0c)
pretraining is done good but getting errors.

**Comment by AllyourBaseBelongToUs** [comment]
Had the same error when using input text files which didnt have enough data and also when Augmentoolkit and the underlying LLM decided the data was not "worthy for questions" (check the folder with the same name there are files which say what and why)

Ive tried the following solutions which worked individually for me

- adding more data, more text documents (it can handle more than one file)
- Fiddling with the temperature of the AI model
- retrying a few times from scratch

another thing i did was just change the files and say its Worthy for questions, though the results have been hit or miss

**Comment by e-p-armstrong** [comment]
Hi!

Sorry for missing your issue for so long, had a crazy month over here. I appreciate your thorough error reporting.

There's recently been an update that lets you skip the filtering step entirely (under "SKIP" turn "FILTER_CHUNKS" on). This should help overcome the issue where your documents are something the AI doesn't really consider to be "traditional" educational questions.

Let me know if you're still encountering any problems, my schedule's stabilizing so I'll do my best to help you speedily.

And thanks for using Augmentoolkit!
