### ISSUE TITLE
Missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by atisharma** [e-p-armstrong/augmentoolkit#55]
I'm working on a dockerfile and I found that the following dependencies are unlisted.

```
pdf2image
selenium
textract
python-docx
```

The textract one is nasty because the latest version 1.6.5 on pypi is broken. There is a fork, though, `textract-py3` which is fixed.

Also, `libtesseract` is required on the system. On debian/ubuntu I think it's `libtesseract-dev` and `tesseract-ocr` and whichever languages you need.

With these extra dependencies I was able to start augmentoolkit in a docker image, which indicates it would complete the list.

**Comment by e-p-armstrong** [comment]
Hey, thanks very much for bringing this to my attention! Can't believe I went and released without checking the darn requirements. Adding a fix right now, will be live in a few.

**Comment by e-p-armstrong** [comment]
Should be fixed now! Tested on my end with a fresh conda env, let me know if it works for you.

**Comment by atisharma** [comment]
Seems OK!
