### ISSUE TITLE
ERROR!! Trying to convert a logging directory to a dataset when that directory does not exist

### ISSUE THREAD

**Issue by SilverSeed93** [e-p-armstrong/augmentoolkit#57]
I am getting the error:
ERROR!! Trying to convert a logging directory to a dataset when that directory does not exist

Checking the folder augmentoolkit\original\output - indeed the folder it is looking for isn't there. 

I'm unsure if this is due to other parts of the job not writing it there?

Attempted with a single text file that I've attached here along with the output from the console.
   

[inputDocument.txt](https://github.com/user-attachments/files/17178298/inputDocument.txt)
[workLog.txt](https://github.com/user-attachments/files/17178299/workLog.txt)

**Comment by e-p-armstrong** [comment]
Looks like all questions are failing the validation checks:
```
-------------- QUESTIONS CREATED ------------- STATS SO FAR (may be wrong if run was continued from interruption):
Nones: 10
Non-nones: 0
Total: 10
---------------- ONTO REVISION ------------------
```
All 10 of the questions that were created failed to get past the validation. Judging by the logging, this seems to be the result of the model used not following the output format well enough. What model are you using?

**Comment by SilverSeed93** [comment]
> What model are you using?

I've been stuck using ollmaa. I've tried the following ollama models:
llama3.1:latest
mistral:latest
solar:latest

**Comment by SilverSeed93** [comment]
I'll close this off. I'm not sure what I did, but I'm starting to get results now. Still using ollama iwth llama3.1 7b. Sorry for the confusion.
