### ISSUE TITLE
KeyError: 'CONVERSATION_GENERATION'

### ISSUE THREAD

**Issue by Lufasoch** [e-p-armstrong/augmentoolkit#59]
Hi, I cloned and installed the requirements, but when I run the run_augmentoolkit.py I get this error.

I am using a conda env, in a windows os

(augmentoolkit) E:\Software\AI\Text\augmentoolkit>python run_augmentoolkit.py
Augmentoolkit is starting to run! If this is your first time running this it might take a few moments to start due to imports and such.
Traceback (most recent call last):
  File "E:\Software\AI\Text\augmentoolkit\original\processing.py", line 422, in <module>
    asyncio.run(main())
  File "C:\Users\lufas\anaconda3\envs\augmentoolkit\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lufas\anaconda3\envs\augmentoolkit\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lufas\anaconda3\envs\augmentoolkit\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Software\AI\Text\augmentoolkit\original\processing.py", line 42, in main
    from original import steps
  File "E:\Software\AI\Text\augmentoolkit\original\steps.py", line 66, in <module>
    SKIP_CONVERSATION_GENERATION = parse_bool(obj_conf["SKIP"]["CONVERSATION_GENERATION"]) # useful if you're generating "tight" data only.
                                              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'CONVERSATION_GENERATION'

**Comment by e-p-armstrong** [comment]
Can I see your config.yaml? It might be missing a required key, I just checked the default config and confirmed it's there so maybe something's wrong with a customization of it?

**Comment by Lufasoch** [comment]
Yes of course, as a side note I followed the video "Generating LLM Data on Your Computer"
https://www.youtube.com/watch?v=_jA4gRFvZ9o

I haven't modified the files yet, I did it at first but found an error so I tried with the unmodified files.

super_config.yaml
pipeline_order:
  - folder: "original"
    config: "config_overrides/text-generation-webui/tgen-config-normal.yaml"
    
tgen-config-normal.yaml
API:
  API_KEY: your-key-here
  BASE_URL: http://127.0.0.1:5000/v1
  LARGE_LOGICAL_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
  LOGICAL_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: False
  PUSH_TO_HUB: False
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: False
SKIP:
  ANSWER_RELEVANCY_CHECK: False
  FILTER_CHUNKS: False
  QUESTION_CHECK: False
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 3
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: True
  FINAL_ASSISTANT_PROMPT_NO_RAG: 'You are a helpful AI assistant.

    '
  FINAL_ASSISTANT_PROMPT_RAG: 'You are a helpful AI assistant.


    Context information is below:


    ----------------------

    {data}

    '
  MODE: api
  STOP: True
  SUBSET_SIZE: 15
  USE_FILENAMES: False
  USE_SUBSET: False

**Comment by Lufasoch** [comment]
I just had time to check this, you were very right @e-p-armstrong it was an issue with missing keys, I copied the missing ones from the original config file.

Again thanks you!
