### ISSUE TITLE
ModuleNotFoundError: No module named 'augmentoolkit'

### ISSUE THREAD

**Issue by MuhammadBilal848** [e-p-armstrong/augmentoolkit#75]
I am trying to run the tool but am getting this error:

```python
(/home/bil/Downloads/augmentoolkit/augtk) bil@POL-Bil-AI:~/Downloads/augmentoolkit$ python original/processing.py 
Traceback (most recent call last):
  File "/home/bi/Downloads/augmentoolkit/original/processing.py", line 5, in <module>
    from augmentoolkit.generation_functions.process_multiturn_functions import extract_conversation
ModuleNotFoundError: No module named 'augmentoolkit'
```

I tried the following steps to configure the repo and get apis:

1. Cloned git repo.
2. Made a conda environment using python 3.11 `conda create -p augtk python==3.11-y`.
3. Installed dependencies `pip install -r requirements.txt`.
4. Copied my text data file into the `original / input` folder (deleted other text and pdf files).
5. I edited `config.yaml` and majorly changed the API section to use AI together (Free $5). 
     ```
      API:
        LARGE_MODEL: meta-llama/Meta-Llama-3.1-70B-Instruct
        LARGE_API_KEY: MY_HIDDEN_API
        LARGE_BASE_URL: https://api.together.ai/
        LARGE_MODE: api
        SMALL_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct
        SMALL_BASE_URL: https://api.deepinfra.com/v1/openai
        SMALL_API_KEY: key-here
        SMALL_MODE: api
     ```
6. Ran the `processing.py` file and got the **ModuleNotFoundError**.

**Comment by e-p-armstrong** [comment]
Don't run processing.py, run `run_augmentoolkit.py`

**Comment by MuhammadBilal848** [comment]
> Don't run processing.py, run `run_augmentoolkit.py`

First  i tried running `run_augmentoolkit.py`, I was using the together.ai free API key having $5, it didn't work then I tried with deepinfra ai free API key it has $1.8 but still it did not work and got this error.

Error:
```
  File "/home/bilal/Downloads/augmentoolkit/original/steps.py", line 96, in convert_logging_to_dataset
    raise Exception("ERROR!! Trying to convert a logging directory to a dataset, when that directory does not exist!")
Exception: ERROR!! Trying to convert a logging directory to a dataset, when that directory does not exist!
```

**Comment by MuhammadBilal848** [comment]
@e-p-armstrong ??????
